#!/bin/bash

cookie=~/.rapid-dl/cookies/rapidshare
DEBUG=0
wget_load="wget --load-cookies $cookie"
logdir=~/.rapid-dl/logs
tempfile=~/.rapid-dl/tmp

function debug_echo {
    if [ $DEBUG -eq 1 ]; then
        echo $1
    fi
}

function download_url {
    if [ ! -f $cookie ]; then
        echo "Could not find rapidshare cookie. Stopping."
        echo "Run rapid-cookie [USER] [PASSWORD]"
        exit
    fi

    if [ ! -d $logdir ]; then
        mkdir -p $logdir
    fi

    # Find the server URL
    $wget_load -q $1 -O $tempfile
    server=`grep -m 1 action= $tempfile | cut -d '"' -f 4`

    # Find the actual URL of the file
    $wget_load -q --post-data=dl.start=PREMIUM $server -O $tempfile
    url=`grep /files $tempfile | tail -1 | cut -d "'" -f 2`

    filename=`basename $url`
    
    debug_echo "URL-> $url"
    echo -ne "Downloading '$filename'"

    logfile=$logdir/$filename.log
    $wget_load -b $url -o$logfile -O$filename | cut -d , -f 2 | sed 's/Out/---> Out/'

    # Cleanup
    if [ -f $tempfile ] ; then
        rm $tempfile
    fi
}

function parse_file {
    echo Parsing file \'$1\'...
    while read url
    do
        download_url $url
    done < $1
}

if [ $# -ne 1 ]
then
    echo "USAGE: rapid-dl [FILE|URL]"
elif [ -f $1 ]
then
    parse_file $1
else
    download_url $1
fi
