#!/bin/bash

# Cancel a rapidshare download

if [ $# -ne 1 ]
then
    echo "USAGE: ./rapid-cancel [FILE]"
    exit
fi

logdir=~/.rapid-dl/logs

# Assumes the log file and downloaded file are in the same directory
if [ -f $1 ]
then
    pid=`ps ax | grep wget | grep $1 | cut -d\  -f 1`
    [ "$pid" != "" ] && echo "Killing pid $pid" && kill -9 $pid
    log=$logdir/$1.log
    [ -f $log ] && echo "Removing log '$log'" && rm $log
    read -p "Do you want to delete the file [y/n]? "
    [ "$REPLY" == "y" ] && rm $1
fi